### ISSUE TITLE
Website doesn't link to the spec's GitHub repo when using a mobile browser

### ISSUE THREAD

**Issue by cvrebert** [jmapio/jmapio.github.io#1]

**Comment by neilj** [comment]
You mean, other than the "Fork me on GitHub" banner in the top right of every page…?

**Comment by cvrebert** [comment]
You're hiding that link on mobile browsers: 
https://github.com/jmapio/jmapio.github.io/blob/488e1ee20a9971946a83994f22590c879b0d254a/main.css#L262

**Comment by neilj** [comment]
Fair point. I think we need an extra entry in the FAQ (homepage) anyway with a link to the mailing list and the GitHub account.

**Comment by cvrebert** [comment]
Or in a footer perhaps.
