### ISSUE TITLE
meli is not developed any more, and links to its website are dead

### ISSUE THREAD

**Issue by ghost** [jmapio/jmapio.github.io#20]
This page refers to the `meli` console jmap client: https://jmap.io/software.html

However, the website is dead, and the github project is archived.

**Comment by marclaporte** [comment]
https://meli-email.org/ loads fine.

https://github.com/meli/meli/ has plenty of activity, and a release one month ago: https://github.com/meli/meli/releases/tag/v0.8.5

I created https://openhub.net/p/meli-email so we get more stats.

This issue can be closed.
