### ISSUE TITLE
Broken banner link leads to 404 page

### ISSUE THREAD

**Issue by antoson** [jmapio/jmapio.github.io#22]
Hi 😊,
the top banner link for Digital Citizen Podcast on jmap.io leads to a 404 page.

["Listen to Fastmail CEO Bron Gondwana talk about JMAP on the Digital Citizen Podcast"](https://www.fastmail.com/digitalcitizen/open-internet-standards-with-bron-gondwana/)

![Screenshot 2023-03-05 161545](https://user-images.githubusercontent.com/36371990/222966348-d4cc9741-90c1-426c-b36f-8e10288ee875.png)

**Comment by rjbs** [comment]
Thanks!  I've corrected the link.
