### ISSUE TITLE
JMAP in the news: add a new section

### ISSUE THREAD

**Issue by marclaporte** [jmapio/jmapio.github.io#4]
I propose a new section / tab for all the media coverage we got (Hackers News, etc). My team can take the lead on this. Please just confirm you like the idea.

Thanks!

**Comment by neilj** [comment]
Sure. A collection of articles about JMAP sounds useful.

**Comment by marclaporte** [comment]
ok, we will prepare a merge request. Will take a little time but we are on it. Thanks!

**Comment by Tbenito** [comment]
The new tab for jmap media coverage has been added.  It only remains to merge the work.
 [click to see the pull-request](https://github.com/jmapio/jmapio.github.io/pull/5)

**Comment by marclaporte** [comment]
It's live:
https://jmap.io/news.html
